# See https://github.com/unicode-org/unicodetools/blob/main/docs/data-workflow.md#publication

# Test locally with https://github.com/nektos/act:
#   act --workflows .github/workflows/publish-ucd.yml --input mode=Alpha

name: Publish UCD

run-name: "${{ github.workflow }}: ${{ inputs.mode }}"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: Publication mode
        type: choice
        options:
          - Snapshot
          - Alpha
          - Beta
        default: Snapshot

env:
  COPY_YEAR: "2024"
  UNI_VER: "17.0.0"
  EMOJI_VER: "17.0"
  TR10_REV: "tr10-52" # UTS #10 release revision number to be used in CollationTest.html: One more than the last release revision number.
  MODE: ${{ inputs.mode }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows
            unicodetools/data/ucd/dev
            unicodetools/data/emoji/dev
            unicodetools/data/idna/dev
            unicodetools/data/idna/idna2008derived
      - run: .github/workflows/publish-ucd.sh
      - uses: actions/upload-artifact@v4
        with:
          path: dist
